<?php
/** Install and migrate database schema. @package ByaheroChixRMS */
if ( ! defined( 'ABSPATH' ) ) { exit; }
class BC_RMS_Installer {
    public static function activate(){ self::install(); self::roles(); }
    public static function maybe_upgrade(){ if(version_compare((string)get_option('bc_rms_db_version','0.0.0'),BC_RMS_DB_VERSION,'<')) { self::install(); self::roles(); } }
    private static function install(){ self::tables(); self::seed(); update_option('bc_rms_db_version',BC_RMS_DB_VERSION); }
    private static function tables(){
        global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $c=$wpdb->get_charset_collate(); $t=fn($n)=>BC_RMS_DB::table($n); $sql=[];
        $sql[]="CREATE TABLE {$t('units')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,name VARCHAR(50) NOT NULL,symbol VARCHAR(20) NOT NULL,unit_type VARCHAR(30) NOT NULL,factor_to_base DECIMAL(18,8) NOT NULL DEFAULT 1,is_base TINYINT(1) NOT NULL DEFAULT 0,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),UNIQUE KEY name (name),KEY unit_type (unit_type)) $c;";
        $sql[]="CREATE TABLE {$t('unit_conversions')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,from_unit_id BIGINT UNSIGNED NOT NULL,to_unit_id BIGINT UNSIGNED NOT NULL,conversion_factor DECIMAL(18,8) NOT NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),UNIQUE KEY conversion_pair (from_unit_id,to_unit_id)) $c;";
        $sql[]="CREATE TABLE {$t('ingredient_categories')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,name VARCHAR(100) NOT NULL,description TEXT NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),UNIQUE KEY name (name)) $c;";
        $sql[]="CREATE TABLE {$t('ingredients')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,name VARCHAR(150) NOT NULL,category_id BIGINT UNSIGNED NULL,description TEXT NULL,base_unit_id BIGINT UNSIGNED NOT NULL,minimum_stock DECIMAL(14,4) NOT NULL DEFAULT 0,reorder_level DECIMAL(14,4) NOT NULL DEFAULT 0,track_inventory TINYINT(1) NOT NULL DEFAULT 1,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY name (name),KEY category_id (category_id),KEY base_unit_id (base_unit_id)) $c;";
        $sql[]="CREATE TABLE {$t('suppliers')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,name VARCHAR(150) NOT NULL,contact_person VARCHAR(150) NULL,phone VARCHAR(50) NULL,email VARCHAR(150) NULL,address TEXT NULL,lead_time_days INT NOT NULL DEFAULT 0,payment_terms VARCHAR(100) NULL,notes TEXT NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY name (name)) $c;";
        $sql[]="CREATE TABLE {$t('supplier_items')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,supplier_id BIGINT UNSIGNED NOT NULL,ingredient_id BIGINT UNSIGNED NOT NULL,purchase_unit_id BIGINT UNSIGNED NOT NULL,purchase_qty DECIMAL(14,4) NOT NULL,purchase_price DECIMAL(14,2) NOT NULL,minimum_order DECIMAL(14,4) NULL,lead_time_days INT NULL,preferred TINYINT(1) NOT NULL DEFAULT 0,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY supplier_id (supplier_id),KEY ingredient_id (ingredient_id)) $c;";
        $sql[]="CREATE TABLE {$t('settings')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,setting_key VARCHAR(150) NOT NULL,setting_value LONGTEXT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY setting_key (setting_key)) $c;";
        $sql[]="CREATE TABLE {$t('recipes')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,name VARCHAR(150) NOT NULL,description TEXT NULL,yield_qty DECIMAL(14,4) NOT NULL DEFAULT 1,yield_unit_id BIGINT UNSIGNED NULL,servings DECIMAL(14,4) NOT NULL DEFAULT 1,waste_percent DECIMAL(8,4) NOT NULL DEFAULT 0,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY name (name),KEY active (active)) $c;";
        $sql[]="CREATE TABLE {$t('recipe_items')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,recipe_id BIGINT UNSIGNED NOT NULL,ingredient_id BIGINT UNSIGNED NOT NULL,quantity DECIMAL(14,4) NOT NULL,unit_id BIGINT UNSIGNED NOT NULL,notes VARCHAR(255) NULL,sort_order INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY recipe_id (recipe_id),KEY ingredient_id (ingredient_id)) $c;";
        $sql[]="CREATE TABLE {$t('product_categories')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,name VARCHAR(100) NOT NULL,description TEXT NULL,sort_order INT NOT NULL DEFAULT 0,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),UNIQUE KEY name (name),KEY active (active),KEY sort_order (sort_order)) $c;";
        $sql[]="CREATE TABLE {$t('products')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,sku VARCHAR(80) NULL,name VARCHAR(150) NOT NULL,category_id BIGINT UNSIGNED NULL,recipe_id BIGINT UNSIGNED NULL,description TEXT NULL,selling_price DECIMAL(14,2) NOT NULL DEFAULT 0,pos_enabled TINYINT(1) NOT NULL DEFAULT 1,active TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),UNIQUE KEY sku (sku),KEY name (name),KEY category_id (category_id),KEY recipe_id (recipe_id),KEY active (active),KEY pos_enabled (pos_enabled)) $c;";
        $sql[]="CREATE TABLE {$t('packaging')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,name VARCHAR(150) NOT NULL,unit_cost DECIMAL(14,4) NOT NULL DEFAULT 0,notes TEXT NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY name (name),KEY active (active)) $c;";
        $sql[]="CREATE TABLE {$t('product_packaging')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,product_id BIGINT UNSIGNED NOT NULL,packaging_id BIGINT UNSIGNED NOT NULL,quantity DECIMAL(14,4) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),UNIQUE KEY product_packaging (product_id,packaging_id),KEY product_id (product_id),KEY packaging_id (packaging_id)) $c;";
        $sql[]="CREATE TABLE {$t('product_variants')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,product_id BIGINT UNSIGNED NOT NULL,name VARCHAR(100) NOT NULL,sku VARCHAR(80) NULL,price_adjustment DECIMAL(14,2) NOT NULL DEFAULT 0,cost_adjustment DECIMAL(14,4) NOT NULL DEFAULT 0,default_variant TINYINT(1) NOT NULL DEFAULT 0,active TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),UNIQUE KEY sku (sku),KEY product_id (product_id),KEY active (active)) $c;";
        $sql[]="CREATE TABLE {$t('modifier_groups')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,name VARCHAR(120) NOT NULL,selection_type VARCHAR(20) NOT NULL DEFAULT 'multiple',min_select INT NOT NULL DEFAULT 0,max_select INT NOT NULL DEFAULT 0,required_group TINYINT(1) NOT NULL DEFAULT 0,active TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY active (active)) $c;";
        $sql[]="CREATE TABLE {$t('modifiers')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,group_id BIGINT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,price_adjustment DECIMAL(14,2) NOT NULL DEFAULT 0,cost_adjustment DECIMAL(14,4) NOT NULL DEFAULT 0,active TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY group_id (group_id),KEY active (active)) $c;";
        $sql[]="CREATE TABLE {$t('product_modifier_groups')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,product_id BIGINT UNSIGNED NOT NULL,group_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),UNIQUE KEY product_group (product_id,group_id),KEY product_id (product_id),KEY group_id (group_id)) $c;";
        $sql[]="CREATE TABLE {$t('orders')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,order_number VARCHAR(40) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'completed',order_type VARCHAR(20) NOT NULL DEFAULT 'dine_in',subtotal DECIMAL(14,2) NOT NULL DEFAULT 0,discount_total DECIMAL(14,2) NOT NULL DEFAULT 0,tax_total DECIMAL(14,2) NOT NULL DEFAULT 0,total DECIMAL(14,2) NOT NULL DEFAULT 0,payment_method VARCHAR(30) NOT NULL DEFAULT 'cash',amount_tendered DECIMAL(14,2) NOT NULL DEFAULT 0,change_due DECIMAL(14,2) NOT NULL DEFAULT 0,cashier_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,notes TEXT NULL,completed_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),UNIQUE KEY order_number (order_number),KEY status (status),KEY created_at (created_at),KEY cashier_user_id (cashier_user_id)) $c;";
        $sql[]="CREATE TABLE {$t('order_items')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,order_id BIGINT UNSIGNED NOT NULL,product_id BIGINT UNSIGNED NOT NULL,variant_id BIGINT UNSIGNED NULL,product_name VARCHAR(150) NOT NULL,variant_name VARCHAR(100) NULL,sku VARCHAR(80) NULL,quantity DECIMAL(12,3) NOT NULL DEFAULT 1,unit_price DECIMAL(14,2) NOT NULL DEFAULT 0,unit_cost DECIMAL(14,4) NOT NULL DEFAULT 0,line_total DECIMAL(14,2) NOT NULL DEFAULT 0,notes VARCHAR(255) NULL,created_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY order_id (order_id),KEY product_id (product_id)) $c;";
        $sql[]="CREATE TABLE {$t('order_item_modifiers')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,order_item_id BIGINT UNSIGNED NOT NULL,modifier_id BIGINT UNSIGNED NOT NULL,modifier_name VARCHAR(120) NOT NULL,price_adjustment DECIMAL(14,2) NOT NULL DEFAULT 0,cost_adjustment DECIMAL(14,4) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY order_item_id (order_item_id),KEY modifier_id (modifier_id)) $c;";
        $sql[]="CREATE TABLE {$t('inventory_movements')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,ingredient_id BIGINT UNSIGNED NOT NULL,movement_type VARCHAR(30) NOT NULL,quantity_delta DECIMAL(16,4) NOT NULL DEFAULT 0,unit_cost DECIMAL(14,4) NULL,reference_type VARCHAR(30) NULL,reference_id BIGINT UNSIGNED NULL,reference_code VARCHAR(80) NULL,notes VARCHAR(255) NULL,user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY ingredient_id (ingredient_id),KEY movement_type (movement_type),KEY reference (reference_type,reference_id),KEY created_at (created_at)) $c;";
        $sql[]="CREATE TABLE {$t('inventory_receipts')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,receipt_number VARCHAR(50) NOT NULL,supplier_id BIGINT UNSIGNED NULL,reference_no VARCHAR(100) NULL,receipt_date DATE NOT NULL,notes TEXT NULL,user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),UNIQUE KEY receipt_number (receipt_number),KEY supplier_id (supplier_id),KEY receipt_date (receipt_date)) $c;";
        $sql[]="CREATE TABLE {$t('inventory_receipt_items')} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uuid CHAR(36) NOT NULL,receipt_id BIGINT UNSIGNED NOT NULL,ingredient_id BIGINT UNSIGNED NOT NULL,quantity_base DECIMAL(16,4) NOT NULL,unit_cost_base DECIMAL(14,4) NOT NULL DEFAULT 0,purchase_quantity DECIMAL(14,4) NOT NULL DEFAULT 0,purchase_unit_id BIGINT UNSIGNED NOT NULL,purchase_price DECIMAL(14,2) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,PRIMARY KEY (id),UNIQUE KEY uuid (uuid),KEY receipt_id (receipt_id),KEY ingredient_id (ingredient_id)) $c;";
        foreach($sql as $q) dbDelta($q);
    }
    private static function seed(){ global $wpdb; $u=BC_RMS_DB::table('units');$n=BC_RMS_DB::now();$units=[['gram','g','weight',1,1],['kilogram','kg','weight',1000,0],['milliliter','ml','volume',1,1],['liter','L','volume',1000,0],['piece','pc','count',1,1],['pack','pack','package',1,1],['box','box','package',1,1],['bottle','btl','package',1,1],['case','case','package',1,1]];foreach($units as $x){if(!$wpdb->get_var($wpdb->prepare("SELECT id FROM $u WHERE name=%s",$x[0])))$wpdb->insert($u,['uuid'=>BC_RMS_DB::uuid(),'name'=>$x[0],'symbol'=>$x[1],'unit_type'=>$x[2],'factor_to_base'=>$x[3],'is_base'=>$x[4],'active'=>1,'created_at'=>$n,'updated_at'=>$n]);} $s=BC_RMS_DB::table('settings');foreach(['business_name'=>'BYAHERO CHIX','currency'=>'PHP','currency_symbol'=>'₱','timezone'=>'Asia/Manila','target_food_cost'=>'35','target_margin'=>'40'] as $k=>$v){if(!$wpdb->get_var($wpdb->prepare("SELECT id FROM $s WHERE setting_key=%s",$k)))$wpdb->insert($s,['setting_key'=>$k,'setting_value'=>$v,'created_at'=>$n,'updated_at'=>$n]);}}
    private static function roles(){ $caps=['bc_view_rms','bc_manage_ingredients','bc_manage_units','bc_manage_suppliers','bc_manage_settings','bc_manage_recipes','bc_manage_products','bc_manage_packaging','bc_manage_modifiers','bc_use_pos','bc_view_orders','bc_manage_inventory','bc_view_inventory'];$a=get_role('administrator');if($a)foreach($caps as $c)$a->add_cap($c);$m=add_role('bc_manager','BC Manager',['read'=>true])?:get_role('bc_manager');if($m)foreach($caps as $c)$m->add_cap($c); }
}
